// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/deposit/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.deposit.v1";

export interface EventAdd {
  address: string;
  coins: string;
}

export interface EventSubtract {
  address: string;
  coins: string;
}

function createBaseEventAdd(): EventAdd {
  return { address: "", coins: "" };
}

export const EventAdd: MessageFns<EventAdd> = {
  encode(message: EventAdd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.coins !== "") {
      writer.uint32(18).string(message.coins);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventAdd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventAdd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.coins = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventAdd {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      coins: isSet(object.coins) ? globalThis.String(object.coins) : "",
    };
  },

  toJSON(message: EventAdd): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.coins !== "") {
      obj.coins = message.coins;
    }
    return obj;
  },

  create(base?: DeepPartial<EventAdd>): EventAdd {
    return EventAdd.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventAdd>): EventAdd {
    const message = createBaseEventAdd();
    message.address = object.address ?? "";
    message.coins = object.coins ?? "";
    return message;
  },
};

function createBaseEventSubtract(): EventSubtract {
  return { address: "", coins: "" };
}

export const EventSubtract: MessageFns<EventSubtract> = {
  encode(message: EventSubtract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.coins !== "") {
      writer.uint32(18).string(message.coins);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventSubtract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventSubtract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.coins = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventSubtract {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      coins: isSet(object.coins) ? globalThis.String(object.coins) : "",
    };
  },

  toJSON(message: EventSubtract): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.coins !== "") {
      obj.coins = message.coins;
    }
    return obj;
  },

  create(base?: DeepPartial<EventSubtract>): EventSubtract {
    return EventSubtract.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventSubtract>): EventSubtract {
    const message = createBaseEventSubtract();
    message.address = object.address ?? "";
    message.coins = object.coins ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
