// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/session/v3/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.session.v3";

export interface EventEnd {
  sessionId: Long;
  accAddress: string;
  nodeAddress: string;
}

export interface EventUpdateDetails {
  sessionId: Long;
  accAddress: string;
  nodeAddress: string;
  downloadBytes: string;
  uploadBytes: string;
  duration: string;
}

export interface EventUpdateStatus {
  sessionId: Long;
  accAddress: string;
  nodeAddress: string;
  status: string;
}

function createBaseEventEnd(): EventEnd {
  return { sessionId: Long.UZERO, accAddress: "", nodeAddress: "" };
}

export const EventEnd: MessageFns<EventEnd> = {
  encode(message: EventEnd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId.toString());
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventEnd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventEnd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventEnd {
    return {
      sessionId: isSet(object.sessionId)
        ? Long.fromValue(object.sessionId)
        : isSet(object.session_id)
        ? Long.fromValue(object.session_id)
        : Long.UZERO,
      accAddress: isSet(object.accAddress)
        ? globalThis.String(object.accAddress)
        : isSet(object.acc_address)
        ? globalThis.String(object.acc_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
    };
  },

  toJSON(message: EventEnd): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    return obj;
  },

  create(base?: DeepPartial<EventEnd>): EventEnd {
    return EventEnd.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventEnd>): EventEnd {
    const message = createBaseEventEnd();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    return message;
  },
};

function createBaseEventUpdateDetails(): EventUpdateDetails {
  return { sessionId: Long.UZERO, accAddress: "", nodeAddress: "", downloadBytes: "", uploadBytes: "", duration: "" };
}

export const EventUpdateDetails: MessageFns<EventUpdateDetails> = {
  encode(message: EventUpdateDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId.toString());
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    if (message.downloadBytes !== "") {
      writer.uint32(34).string(message.downloadBytes);
    }
    if (message.uploadBytes !== "") {
      writer.uint32(42).string(message.uploadBytes);
    }
    if (message.duration !== "") {
      writer.uint32(50).string(message.duration);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.downloadBytes = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.uploadBytes = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.duration = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateDetails {
    return {
      sessionId: isSet(object.sessionId)
        ? Long.fromValue(object.sessionId)
        : isSet(object.session_id)
        ? Long.fromValue(object.session_id)
        : Long.UZERO,
      accAddress: isSet(object.accAddress)
        ? globalThis.String(object.accAddress)
        : isSet(object.acc_address)
        ? globalThis.String(object.acc_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      downloadBytes: isSet(object.downloadBytes)
        ? globalThis.String(object.downloadBytes)
        : isSet(object.download_bytes)
        ? globalThis.String(object.download_bytes)
        : "",
      uploadBytes: isSet(object.uploadBytes)
        ? globalThis.String(object.uploadBytes)
        : isSet(object.upload_bytes)
        ? globalThis.String(object.upload_bytes)
        : "",
      duration: isSet(object.duration) ? globalThis.String(object.duration) : "",
    };
  },

  toJSON(message: EventUpdateDetails): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.downloadBytes !== "") {
      obj.downloadBytes = message.downloadBytes;
    }
    if (message.uploadBytes !== "") {
      obj.uploadBytes = message.uploadBytes;
    }
    if (message.duration !== "") {
      obj.duration = message.duration;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    return EventUpdateDetails.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    const message = createBaseEventUpdateDetails();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.downloadBytes = object.downloadBytes ?? "";
    message.uploadBytes = object.uploadBytes ?? "";
    message.duration = object.duration ?? "";
    return message;
  },
};

function createBaseEventUpdateStatus(): EventUpdateStatus {
  return { sessionId: Long.UZERO, accAddress: "", nodeAddress: "", status: "" };
}

export const EventUpdateStatus: MessageFns<EventUpdateStatus> = {
  encode(message: EventUpdateStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId.toString());
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateStatus {
    return {
      sessionId: isSet(object.sessionId)
        ? Long.fromValue(object.sessionId)
        : isSet(object.session_id)
        ? Long.fromValue(object.session_id)
        : Long.UZERO,
      accAddress: isSet(object.accAddress)
        ? globalThis.String(object.accAddress)
        : isSet(object.acc_address)
        ? globalThis.String(object.acc_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: EventUpdateStatus): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    return EventUpdateStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    const message = createBaseEventUpdateStatus();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
