// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/session/v3/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { Duration } from "../../../google/protobuf/duration";

export const protobufPackage = "sentinel.session.v3";

export interface Params {
  maxGigabytes: Long;
  minGigabytes: Long;
  maxHours: Long;
  minHours: Long;
  proofVerificationEnabled: boolean;
  stakingShare: string;
  statusTimeout?: Duration | undefined;
}

function createBaseParams(): Params {
  return {
    maxGigabytes: Long.ZERO,
    minGigabytes: Long.ZERO,
    maxHours: Long.ZERO,
    minHours: Long.ZERO,
    proofVerificationEnabled: false,
    stakingShare: "",
    statusTimeout: undefined,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.maxGigabytes.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.maxGigabytes.toString());
    }
    if (!message.minGigabytes.equals(Long.ZERO)) {
      writer.uint32(16).int64(message.minGigabytes.toString());
    }
    if (!message.maxHours.equals(Long.ZERO)) {
      writer.uint32(24).int64(message.maxHours.toString());
    }
    if (!message.minHours.equals(Long.ZERO)) {
      writer.uint32(32).int64(message.minHours.toString());
    }
    if (message.proofVerificationEnabled !== false) {
      writer.uint32(40).bool(message.proofVerificationEnabled);
    }
    if (message.stakingShare !== "") {
      writer.uint32(50).string(message.stakingShare);
    }
    if (message.statusTimeout !== undefined) {
      Duration.encode(message.statusTimeout, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxGigabytes = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minGigabytes = Long.fromString(reader.int64().toString());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxHours = Long.fromString(reader.int64().toString());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minHours = Long.fromString(reader.int64().toString());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.proofVerificationEnabled = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.stakingShare = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.statusTimeout = Duration.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxGigabytes: isSet(object.maxGigabytes)
        ? Long.fromValue(object.maxGigabytes)
        : isSet(object.max_gigabytes)
        ? Long.fromValue(object.max_gigabytes)
        : Long.ZERO,
      minGigabytes: isSet(object.minGigabytes)
        ? Long.fromValue(object.minGigabytes)
        : isSet(object.min_gigabytes)
        ? Long.fromValue(object.min_gigabytes)
        : Long.ZERO,
      maxHours: isSet(object.maxHours)
        ? Long.fromValue(object.maxHours)
        : isSet(object.max_hours)
        ? Long.fromValue(object.max_hours)
        : Long.ZERO,
      minHours: isSet(object.minHours)
        ? Long.fromValue(object.minHours)
        : isSet(object.min_hours)
        ? Long.fromValue(object.min_hours)
        : Long.ZERO,
      proofVerificationEnabled: isSet(object.proofVerificationEnabled)
        ? globalThis.Boolean(object.proofVerificationEnabled)
        : isSet(object.proof_verification_enabled)
        ? globalThis.Boolean(object.proof_verification_enabled)
        : false,
      stakingShare: isSet(object.stakingShare)
        ? globalThis.String(object.stakingShare)
        : isSet(object.staking_share)
        ? globalThis.String(object.staking_share)
        : "",
      statusTimeout: isSet(object.statusTimeout)
        ? Duration.fromJSON(object.statusTimeout)
        : isSet(object.status_timeout)
        ? Duration.fromJSON(object.status_timeout)
        : undefined,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (!message.maxGigabytes.equals(Long.ZERO)) {
      obj.maxGigabytes = (message.maxGigabytes || Long.ZERO).toString();
    }
    if (!message.minGigabytes.equals(Long.ZERO)) {
      obj.minGigabytes = (message.minGigabytes || Long.ZERO).toString();
    }
    if (!message.maxHours.equals(Long.ZERO)) {
      obj.maxHours = (message.maxHours || Long.ZERO).toString();
    }
    if (!message.minHours.equals(Long.ZERO)) {
      obj.minHours = (message.minHours || Long.ZERO).toString();
    }
    if (message.proofVerificationEnabled !== false) {
      obj.proofVerificationEnabled = message.proofVerificationEnabled;
    }
    if (message.stakingShare !== "") {
      obj.stakingShare = message.stakingShare;
    }
    if (message.statusTimeout !== undefined) {
      obj.statusTimeout = Duration.toJSON(message.statusTimeout);
    }
    return obj;
  },

  create(base?: DeepPartial<Params>): Params {
    return Params.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Params>): Params {
    const message = createBaseParams();
    message.maxGigabytes = (object.maxGigabytes !== undefined && object.maxGigabytes !== null)
      ? Long.fromValue(object.maxGigabytes)
      : Long.ZERO;
    message.minGigabytes = (object.minGigabytes !== undefined && object.minGigabytes !== null)
      ? Long.fromValue(object.minGigabytes)
      : Long.ZERO;
    message.maxHours = (object.maxHours !== undefined && object.maxHours !== null)
      ? Long.fromValue(object.maxHours)
      : Long.ZERO;
    message.minHours = (object.minHours !== undefined && object.minHours !== null)
      ? Long.fromValue(object.minHours)
      : Long.ZERO;
    message.proofVerificationEnabled = object.proofVerificationEnabled ?? false;
    message.stakingShare = object.stakingShare ?? "";
    message.statusTimeout = (object.statusTimeout !== undefined && object.statusTimeout !== null)
      ? Duration.fromPartial(object.statusTimeout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
