// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/session/v3/session.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { Duration } from "../../../google/protobuf/duration";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { Status, statusFromJSON, statusToJSON } from "../../types/v1/status";

export const protobufPackage = "sentinel.session.v3";

export interface BaseSession {
  id: Long;
  accAddress: string;
  nodeAddress: string;
  downloadBytes: string;
  uploadBytes: string;
  maxBytes: string;
  duration?: Duration | undefined;
  maxDuration?: Duration | undefined;
  status: Status;
  inactiveAt?: Date | undefined;
  startAt?: Date | undefined;
  statusAt?: Date | undefined;
}

function createBaseBaseSession(): BaseSession {
  return {
    id: Long.UZERO,
    accAddress: "",
    nodeAddress: "",
    downloadBytes: "",
    uploadBytes: "",
    maxBytes: "",
    duration: undefined,
    maxDuration: undefined,
    status: 0,
    inactiveAt: undefined,
    startAt: undefined,
    statusAt: undefined,
  };
}

export const BaseSession: MessageFns<BaseSession> = {
  encode(message: BaseSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.id.toString());
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    if (message.downloadBytes !== "") {
      writer.uint32(34).string(message.downloadBytes);
    }
    if (message.uploadBytes !== "") {
      writer.uint32(42).string(message.uploadBytes);
    }
    if (message.maxBytes !== "") {
      writer.uint32(50).string(message.maxBytes);
    }
    if (message.duration !== undefined) {
      Duration.encode(message.duration, writer.uint32(58).fork()).join();
    }
    if (message.maxDuration !== undefined) {
      Duration.encode(message.maxDuration, writer.uint32(66).fork()).join();
    }
    if (message.status !== 0) {
      writer.uint32(72).int32(message.status);
    }
    if (message.inactiveAt !== undefined) {
      Timestamp.encode(toTimestamp(message.inactiveAt), writer.uint32(82).fork()).join();
    }
    if (message.startAt !== undefined) {
      Timestamp.encode(toTimestamp(message.startAt), writer.uint32(90).fork()).join();
    }
    if (message.statusAt !== undefined) {
      Timestamp.encode(toTimestamp(message.statusAt), writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.downloadBytes = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.uploadBytes = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.maxBytes = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.duration = Duration.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.maxDuration = Duration.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.inactiveAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.startAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.statusAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseSession {
    return {
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
      accAddress: isSet(object.accAddress)
        ? globalThis.String(object.accAddress)
        : isSet(object.acc_address)
        ? globalThis.String(object.acc_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      downloadBytes: isSet(object.downloadBytes)
        ? globalThis.String(object.downloadBytes)
        : isSet(object.download_bytes)
        ? globalThis.String(object.download_bytes)
        : "",
      uploadBytes: isSet(object.uploadBytes)
        ? globalThis.String(object.uploadBytes)
        : isSet(object.upload_bytes)
        ? globalThis.String(object.upload_bytes)
        : "",
      maxBytes: isSet(object.maxBytes)
        ? globalThis.String(object.maxBytes)
        : isSet(object.max_bytes)
        ? globalThis.String(object.max_bytes)
        : "",
      duration: isSet(object.duration) ? Duration.fromJSON(object.duration) : undefined,
      maxDuration: isSet(object.maxDuration)
        ? Duration.fromJSON(object.maxDuration)
        : isSet(object.max_duration)
        ? Duration.fromJSON(object.max_duration)
        : undefined,
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      inactiveAt: isSet(object.inactiveAt)
        ? fromJsonTimestamp(object.inactiveAt)
        : isSet(object.inactive_at)
        ? fromJsonTimestamp(object.inactive_at)
        : undefined,
      startAt: isSet(object.startAt)
        ? fromJsonTimestamp(object.startAt)
        : isSet(object.start_at)
        ? fromJsonTimestamp(object.start_at)
        : undefined,
      statusAt: isSet(object.statusAt)
        ? fromJsonTimestamp(object.statusAt)
        : isSet(object.status_at)
        ? fromJsonTimestamp(object.status_at)
        : undefined,
    };
  },

  toJSON(message: BaseSession): unknown {
    const obj: any = {};
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.downloadBytes !== "") {
      obj.downloadBytes = message.downloadBytes;
    }
    if (message.uploadBytes !== "") {
      obj.uploadBytes = message.uploadBytes;
    }
    if (message.maxBytes !== "") {
      obj.maxBytes = message.maxBytes;
    }
    if (message.duration !== undefined) {
      obj.duration = Duration.toJSON(message.duration);
    }
    if (message.maxDuration !== undefined) {
      obj.maxDuration = Duration.toJSON(message.maxDuration);
    }
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.inactiveAt !== undefined) {
      obj.inactiveAt = message.inactiveAt.toISOString();
    }
    if (message.startAt !== undefined) {
      obj.startAt = message.startAt.toISOString();
    }
    if (message.statusAt !== undefined) {
      obj.statusAt = message.statusAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<BaseSession>): BaseSession {
    return BaseSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BaseSession>): BaseSession {
    const message = createBaseBaseSession();
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.downloadBytes = object.downloadBytes ?? "";
    message.uploadBytes = object.uploadBytes ?? "";
    message.maxBytes = object.maxBytes ?? "";
    message.duration = (object.duration !== undefined && object.duration !== null)
      ? Duration.fromPartial(object.duration)
      : undefined;
    message.maxDuration = (object.maxDuration !== undefined && object.maxDuration !== null)
      ? Duration.fromPartial(object.maxDuration)
      : undefined;
    message.status = object.status ?? 0;
    message.inactiveAt = object.inactiveAt ?? undefined;
    message.startAt = object.startAt ?? undefined;
    message.statusAt = object.statusAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = numberToLong(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds.toNumber() || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function numberToLong(number: number) {
  return Long.fromNumber(number);
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
