// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: sentinel/node/v3/events.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "sentinel.node.v3";

export interface EventCreate {
  nodeAddress: string;
  gigabytePrices: string;
  hourlyPrices: string;
  remoteAddrs: string[];
}

export interface EventPay {
  sessionId: Long;
  accAddress: string;
  nodeAddress: string;
  payment: string;
  stakingReward: string;
}

export interface EventRefund {
  sessionId: Long;
  accAddress: string;
  value: string;
}

export interface EventUpdateDetails {
  nodeAddress: string;
  gigabytePrices: string;
  hourlyPrices: string;
  remoteAddrs: string[];
}

export interface EventUpdateStatus {
  nodeAddress: string;
  status: string;
}

export interface EventCreateSession {
  sessionId: Long;
  accAddress: string;
  nodeAddress: string;
  price: string;
  maxBytes: string;
  maxDuration: string;
}

function createBaseEventCreate(): EventCreate {
  return { nodeAddress: "", gigabytePrices: "", hourlyPrices: "", remoteAddrs: [] };
}

export const EventCreate = {
  encode(message: EventCreate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.nodeAddress !== "") {
      writer.uint32(10).string(message.nodeAddress);
    }
    if (message.gigabytePrices !== "") {
      writer.uint32(18).string(message.gigabytePrices);
    }
    if (message.hourlyPrices !== "") {
      writer.uint32(26).string(message.hourlyPrices);
    }
    for (const v of message.remoteAddrs) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventCreate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.gigabytePrices = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.hourlyPrices = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.remoteAddrs.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventCreate {
    return {
      nodeAddress: isSet(object.nodeAddress) ? globalThis.String(object.nodeAddress) : "",
      gigabytePrices: isSet(object.gigabytePrices) ? globalThis.String(object.gigabytePrices) : "",
      hourlyPrices: isSet(object.hourlyPrices) ? globalThis.String(object.hourlyPrices) : "",
      remoteAddrs: globalThis.Array.isArray(object?.remoteAddrs)
        ? object.remoteAddrs.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: EventCreate): unknown {
    const obj: any = {};
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.gigabytePrices !== "") {
      obj.gigabytePrices = message.gigabytePrices;
    }
    if (message.hourlyPrices !== "") {
      obj.hourlyPrices = message.hourlyPrices;
    }
    if (message.remoteAddrs?.length) {
      obj.remoteAddrs = message.remoteAddrs;
    }
    return obj;
  },

  create(base?: DeepPartial<EventCreate>): EventCreate {
    return EventCreate.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventCreate>): EventCreate {
    const message = createBaseEventCreate();
    message.nodeAddress = object.nodeAddress ?? "";
    message.gigabytePrices = object.gigabytePrices ?? "";
    message.hourlyPrices = object.hourlyPrices ?? "";
    message.remoteAddrs = object.remoteAddrs?.map((e) => e) || [];
    return message;
  },
};

function createBaseEventPay(): EventPay {
  return { sessionId: Long.UZERO, accAddress: "", nodeAddress: "", payment: "", stakingReward: "" };
}

export const EventPay = {
  encode(message: EventPay, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId);
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    if (message.payment !== "") {
      writer.uint32(34).string(message.payment);
    }
    if (message.stakingReward !== "") {
      writer.uint32(42).string(message.stakingReward);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventPay {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventPay();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sessionId = reader.uint64() as Long;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.payment = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.stakingReward = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventPay {
    return {
      sessionId: isSet(object.sessionId) ? Long.fromValue(object.sessionId) : Long.UZERO,
      accAddress: isSet(object.accAddress) ? globalThis.String(object.accAddress) : "",
      nodeAddress: isSet(object.nodeAddress) ? globalThis.String(object.nodeAddress) : "",
      payment: isSet(object.payment) ? globalThis.String(object.payment) : "",
      stakingReward: isSet(object.stakingReward) ? globalThis.String(object.stakingReward) : "",
    };
  },

  toJSON(message: EventPay): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.payment !== "") {
      obj.payment = message.payment;
    }
    if (message.stakingReward !== "") {
      obj.stakingReward = message.stakingReward;
    }
    return obj;
  },

  create(base?: DeepPartial<EventPay>): EventPay {
    return EventPay.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventPay>): EventPay {
    const message = createBaseEventPay();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.payment = object.payment ?? "";
    message.stakingReward = object.stakingReward ?? "";
    return message;
  },
};

function createBaseEventRefund(): EventRefund {
  return { sessionId: Long.UZERO, accAddress: "", value: "" };
}

export const EventRefund = {
  encode(message: EventRefund, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId);
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.value !== "") {
      writer.uint32(26).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventRefund {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventRefund();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sessionId = reader.uint64() as Long;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventRefund {
    return {
      sessionId: isSet(object.sessionId) ? Long.fromValue(object.sessionId) : Long.UZERO,
      accAddress: isSet(object.accAddress) ? globalThis.String(object.accAddress) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: EventRefund): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<EventRefund>): EventRefund {
    return EventRefund.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventRefund>): EventRefund {
    const message = createBaseEventRefund();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseEventUpdateDetails(): EventUpdateDetails {
  return { nodeAddress: "", gigabytePrices: "", hourlyPrices: "", remoteAddrs: [] };
}

export const EventUpdateDetails = {
  encode(message: EventUpdateDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.nodeAddress !== "") {
      writer.uint32(10).string(message.nodeAddress);
    }
    if (message.gigabytePrices !== "") {
      writer.uint32(18).string(message.gigabytePrices);
    }
    if (message.hourlyPrices !== "") {
      writer.uint32(26).string(message.hourlyPrices);
    }
    for (const v of message.remoteAddrs) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventUpdateDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.gigabytePrices = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.hourlyPrices = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.remoteAddrs.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateDetails {
    return {
      nodeAddress: isSet(object.nodeAddress) ? globalThis.String(object.nodeAddress) : "",
      gigabytePrices: isSet(object.gigabytePrices) ? globalThis.String(object.gigabytePrices) : "",
      hourlyPrices: isSet(object.hourlyPrices) ? globalThis.String(object.hourlyPrices) : "",
      remoteAddrs: globalThis.Array.isArray(object?.remoteAddrs)
        ? object.remoteAddrs.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: EventUpdateDetails): unknown {
    const obj: any = {};
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.gigabytePrices !== "") {
      obj.gigabytePrices = message.gigabytePrices;
    }
    if (message.hourlyPrices !== "") {
      obj.hourlyPrices = message.hourlyPrices;
    }
    if (message.remoteAddrs?.length) {
      obj.remoteAddrs = message.remoteAddrs;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    return EventUpdateDetails.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    const message = createBaseEventUpdateDetails();
    message.nodeAddress = object.nodeAddress ?? "";
    message.gigabytePrices = object.gigabytePrices ?? "";
    message.hourlyPrices = object.hourlyPrices ?? "";
    message.remoteAddrs = object.remoteAddrs?.map((e) => e) || [];
    return message;
  },
};

function createBaseEventUpdateStatus(): EventUpdateStatus {
  return { nodeAddress: "", status: "" };
}

export const EventUpdateStatus = {
  encode(message: EventUpdateStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.nodeAddress !== "") {
      writer.uint32(10).string(message.nodeAddress);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventUpdateStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateStatus {
    return {
      nodeAddress: isSet(object.nodeAddress) ? globalThis.String(object.nodeAddress) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: EventUpdateStatus): unknown {
    const obj: any = {};
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    return EventUpdateStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    const message = createBaseEventUpdateStatus();
    message.nodeAddress = object.nodeAddress ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseEventCreateSession(): EventCreateSession {
  return { sessionId: Long.UZERO, accAddress: "", nodeAddress: "", price: "", maxBytes: "", maxDuration: "" };
}

export const EventCreateSession = {
  encode(message: EventCreateSession, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.sessionId);
    }
    if (message.accAddress !== "") {
      writer.uint32(18).string(message.accAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    if (message.price !== "") {
      writer.uint32(34).string(message.price);
    }
    if (message.maxBytes !== "") {
      writer.uint32(42).string(message.maxBytes);
    }
    if (message.maxDuration !== "") {
      writer.uint32(50).string(message.maxDuration);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EventCreateSession {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventCreateSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sessionId = reader.uint64() as Long;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.accAddress = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.price = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.maxBytes = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.maxDuration = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventCreateSession {
    return {
      sessionId: isSet(object.sessionId) ? Long.fromValue(object.sessionId) : Long.UZERO,
      accAddress: isSet(object.accAddress) ? globalThis.String(object.accAddress) : "",
      nodeAddress: isSet(object.nodeAddress) ? globalThis.String(object.nodeAddress) : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      maxBytes: isSet(object.maxBytes) ? globalThis.String(object.maxBytes) : "",
      maxDuration: isSet(object.maxDuration) ? globalThis.String(object.maxDuration) : "",
    };
  },

  toJSON(message: EventCreateSession): unknown {
    const obj: any = {};
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (message.accAddress !== "") {
      obj.accAddress = message.accAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.price !== "") {
      obj.price = message.price;
    }
    if (message.maxBytes !== "") {
      obj.maxBytes = message.maxBytes;
    }
    if (message.maxDuration !== "") {
      obj.maxDuration = message.maxDuration;
    }
    return obj;
  },

  create(base?: DeepPartial<EventCreateSession>): EventCreateSession {
    return EventCreateSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventCreateSession>): EventCreateSession {
    const message = createBaseEventCreateSession();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.accAddress = object.accAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.price = object.price ?? "";
    message.maxBytes = object.maxBytes ?? "";
    message.maxDuration = object.maxDuration ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
