// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: sentinel/node/v3/params.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Coin } from "../../../cosmos/base/v1beta1/coin";
import { Duration } from "../../../google/protobuf/duration";
import { Price } from "../../types/v1/price";

export const protobufPackage = "sentinel.node.v3";

export interface Params {
  deposit?: Coin | undefined;
  minGigabytePrices: Price[];
  minHourlyPrices: Price[];
  statusTimeout?: Duration | undefined;
}

function createBaseParams(): Params {
  return { deposit: undefined, minGigabytePrices: [], minHourlyPrices: [], statusTimeout: undefined };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.deposit !== undefined) {
      Coin.encode(message.deposit, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.minGigabytePrices) {
      Price.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.minHourlyPrices) {
      Price.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    if (message.statusTimeout !== undefined) {
      Duration.encode(message.statusTimeout, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.deposit = Coin.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.minGigabytePrices.push(Price.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.minHourlyPrices.push(Price.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.statusTimeout = Duration.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      deposit: isSet(object.deposit) ? Coin.fromJSON(object.deposit) : undefined,
      minGigabytePrices: globalThis.Array.isArray(object?.minGigabytePrices)
        ? object.minGigabytePrices.map((e: any) => Price.fromJSON(e))
        : [],
      minHourlyPrices: globalThis.Array.isArray(object?.minHourlyPrices)
        ? object.minHourlyPrices.map((e: any) => Price.fromJSON(e))
        : [],
      statusTimeout: isSet(object.statusTimeout) ? Duration.fromJSON(object.statusTimeout) : undefined,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.deposit !== undefined) {
      obj.deposit = Coin.toJSON(message.deposit);
    }
    if (message.minGigabytePrices?.length) {
      obj.minGigabytePrices = message.minGigabytePrices.map((e) => Price.toJSON(e));
    }
    if (message.minHourlyPrices?.length) {
      obj.minHourlyPrices = message.minHourlyPrices.map((e) => Price.toJSON(e));
    }
    if (message.statusTimeout !== undefined) {
      obj.statusTimeout = Duration.toJSON(message.statusTimeout);
    }
    return obj;
  },

  create(base?: DeepPartial<Params>): Params {
    return Params.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Params>): Params {
    const message = createBaseParams();
    message.deposit = (object.deposit !== undefined && object.deposit !== null)
      ? Coin.fromPartial(object.deposit)
      : undefined;
    message.minGigabytePrices = object.minGigabytePrices?.map((e) => Price.fromPartial(e)) || [];
    message.minHourlyPrices = object.minHourlyPrices?.map((e) => Price.fromPartial(e)) || [];
    message.statusTimeout = (object.statusTimeout !== undefined && object.statusTimeout !== null)
      ? Duration.fromPartial(object.statusTimeout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
