// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: sentinel/node/v3/session.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { BaseSession } from "../../session/v3/session";
import { Price } from "../../types/v1/price";

export const protobufPackage = "sentinel.node.v3";

export interface Session {
  baseSession?: BaseSession | undefined;
  price?: Price | undefined;
}

function createBaseSession(): Session {
  return { baseSession: undefined, price: undefined };
}

export const Session = {
  encode(message: Session, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.baseSession !== undefined) {
      BaseSession.encode(message.baseSession, writer.uint32(10).fork()).ldelim();
    }
    if (message.price !== undefined) {
      Price.encode(message.price, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Session {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.baseSession = BaseSession.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.price = Price.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      baseSession: isSet(object.baseSession) ? BaseSession.fromJSON(object.baseSession) : undefined,
      price: isSet(object.price) ? Price.fromJSON(object.price) : undefined,
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.baseSession !== undefined) {
      obj.baseSession = BaseSession.toJSON(message.baseSession);
    }
    if (message.price !== undefined) {
      obj.price = Price.toJSON(message.price);
    }
    return obj;
  },

  create(base?: DeepPartial<Session>): Session {
    return Session.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Session>): Session {
    const message = createBaseSession();
    message.baseSession = (object.baseSession !== undefined && object.baseSession !== null)
      ? BaseSession.fromPartial(object.baseSession)
      : undefined;
    message.price = (object.price !== undefined && object.price !== null) ? Price.fromPartial(object.price) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
