// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: osmosis/poolmanager/v1beta1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "osmosis.poolmanager.v1beta1";

export interface SpotPriceRequest {
  poolId: Long;
  baseAssetDenom: string;
  quoteAssetDenom: string;
}

export interface SpotPriceResponse {
  spotPrice: string;
}

function createBaseSpotPriceRequest(): SpotPriceRequest {
  return { poolId: Long.UZERO, baseAssetDenom: "", quoteAssetDenom: "" };
}

export const SpotPriceRequest: MessageFns<SpotPriceRequest> = {
  encode(message: SpotPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.poolId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.poolId.toString());
    }
    if (message.baseAssetDenom !== "") {
      writer.uint32(18).string(message.baseAssetDenom);
    }
    if (message.quoteAssetDenom !== "") {
      writer.uint32(26).string(message.quoteAssetDenom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpotPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpotPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.poolId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.baseAssetDenom = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.quoteAssetDenom = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpotPriceRequest {
    return {
      poolId: isSet(object.poolId)
        ? Long.fromValue(object.poolId)
        : isSet(object.pool_id)
        ? Long.fromValue(object.pool_id)
        : Long.UZERO,
      baseAssetDenom: isSet(object.baseAssetDenom)
        ? globalThis.String(object.baseAssetDenom)
        : isSet(object.base_asset_denom)
        ? globalThis.String(object.base_asset_denom)
        : "",
      quoteAssetDenom: isSet(object.quoteAssetDenom)
        ? globalThis.String(object.quoteAssetDenom)
        : isSet(object.quote_asset_denom)
        ? globalThis.String(object.quote_asset_denom)
        : "",
    };
  },

  toJSON(message: SpotPriceRequest): unknown {
    const obj: any = {};
    if (!message.poolId.equals(Long.UZERO)) {
      obj.poolId = (message.poolId || Long.UZERO).toString();
    }
    if (message.baseAssetDenom !== "") {
      obj.baseAssetDenom = message.baseAssetDenom;
    }
    if (message.quoteAssetDenom !== "") {
      obj.quoteAssetDenom = message.quoteAssetDenom;
    }
    return obj;
  },

  create(base?: DeepPartial<SpotPriceRequest>): SpotPriceRequest {
    return SpotPriceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SpotPriceRequest>): SpotPriceRequest {
    const message = createBaseSpotPriceRequest();
    message.poolId = (object.poolId !== undefined && object.poolId !== null)
      ? Long.fromValue(object.poolId)
      : Long.UZERO;
    message.baseAssetDenom = object.baseAssetDenom ?? "";
    message.quoteAssetDenom = object.quoteAssetDenom ?? "";
    return message;
  },
};

function createBaseSpotPriceResponse(): SpotPriceResponse {
  return { spotPrice: "" };
}

export const SpotPriceResponse: MessageFns<SpotPriceResponse> = {
  encode(message: SpotPriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.spotPrice !== "") {
      writer.uint32(10).string(message.spotPrice);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpotPriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpotPriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.spotPrice = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpotPriceResponse {
    return {
      spotPrice: isSet(object.spotPrice)
        ? globalThis.String(object.spotPrice)
        : isSet(object.spot_price)
        ? globalThis.String(object.spot_price)
        : "",
    };
  },

  toJSON(message: SpotPriceResponse): unknown {
    const obj: any = {};
    if (message.spotPrice !== "") {
      obj.spotPrice = message.spotPrice;
    }
    return obj;
  },

  create(base?: DeepPartial<SpotPriceResponse>): SpotPriceResponse {
    return SpotPriceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SpotPriceResponse>): SpotPriceResponse {
    const message = createBaseSpotPriceResponse();
    message.spotPrice = object.spotPrice ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
