// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: osmosis/protorev/v1beta1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "osmosis.protorev.v1beta1";

export interface QueryGetProtoRevPoolRequest {
  baseDenom: string;
  otherDenom: string;
}

export interface QueryGetProtoRevPoolResponse {
  poolId: Long;
}

function createBaseQueryGetProtoRevPoolRequest(): QueryGetProtoRevPoolRequest {
  return { baseDenom: "", otherDenom: "" };
}

export const QueryGetProtoRevPoolRequest: MessageFns<QueryGetProtoRevPoolRequest> = {
  encode(message: QueryGetProtoRevPoolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baseDenom !== "") {
      writer.uint32(10).string(message.baseDenom);
    }
    if (message.otherDenom !== "") {
      writer.uint32(18).string(message.otherDenom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetProtoRevPoolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetProtoRevPoolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baseDenom = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.otherDenom = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetProtoRevPoolRequest {
    return {
      baseDenom: isSet(object.baseDenom)
        ? globalThis.String(object.baseDenom)
        : isSet(object.base_denom)
        ? globalThis.String(object.base_denom)
        : "",
      otherDenom: isSet(object.otherDenom)
        ? globalThis.String(object.otherDenom)
        : isSet(object.other_denom)
        ? globalThis.String(object.other_denom)
        : "",
    };
  },

  toJSON(message: QueryGetProtoRevPoolRequest): unknown {
    const obj: any = {};
    if (message.baseDenom !== "") {
      obj.baseDenom = message.baseDenom;
    }
    if (message.otherDenom !== "") {
      obj.otherDenom = message.otherDenom;
    }
    return obj;
  },

  create(base?: DeepPartial<QueryGetProtoRevPoolRequest>): QueryGetProtoRevPoolRequest {
    return QueryGetProtoRevPoolRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryGetProtoRevPoolRequest>): QueryGetProtoRevPoolRequest {
    const message = createBaseQueryGetProtoRevPoolRequest();
    message.baseDenom = object.baseDenom ?? "";
    message.otherDenom = object.otherDenom ?? "";
    return message;
  },
};

function createBaseQueryGetProtoRevPoolResponse(): QueryGetProtoRevPoolResponse {
  return { poolId: Long.UZERO };
}

export const QueryGetProtoRevPoolResponse: MessageFns<QueryGetProtoRevPoolResponse> = {
  encode(message: QueryGetProtoRevPoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.poolId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.poolId.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetProtoRevPoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetProtoRevPoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.poolId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetProtoRevPoolResponse {
    return {
      poolId: isSet(object.poolId)
        ? Long.fromValue(object.poolId)
        : isSet(object.pool_id)
        ? Long.fromValue(object.pool_id)
        : Long.UZERO,
    };
  },

  toJSON(message: QueryGetProtoRevPoolResponse): unknown {
    const obj: any = {};
    if (!message.poolId.equals(Long.UZERO)) {
      obj.poolId = (message.poolId || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<QueryGetProtoRevPoolResponse>): QueryGetProtoRevPoolResponse {
    return QueryGetProtoRevPoolResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryGetProtoRevPoolResponse>): QueryGetProtoRevPoolResponse {
    const message = createBaseQueryGetProtoRevPoolResponse();
    message.poolId = (object.poolId !== undefined && object.poolId !== null)
      ? Long.fromValue(object.poolId)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
