export const MsgCreateTypeUrl = "/sentinel.plan.v2.MsgCreateRequest"
export const MsgUpdateStatusTypeUrl = "/sentinel.plan.v2.MsgUpdateStatusRequest"
export const MsgLinkNodeTypeUrl = "/sentinel.plan.v2.MsgLinkNodeRequest"
export const MsgUnlinkNodeTypeUrl = "/sentinel.plan.v2.MsgUnlinkNodeRequest"
export const MsgSubscribeTypeUrl = "/sentinel.plan.v2.MsgSubscribeRequest"
