// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/plan/v3/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.plan.v3";

export interface EventCreate {
  planId: Long;
  provAddress: string;
  bytes: string;
  duration: string;
  prices: string;
  private: boolean;
}

export interface EventLinkNode {
  planId: Long;
  provAddress: string;
  nodeAddress: string;
}

export interface EventUnlinkNode {
  planId: Long;
  provAddress: string;
  nodeAddress: string;
}

export interface EventUpdateDetails {
  planId: Long;
  provAddress: string;
  private: boolean;
}

export interface EventUpdateStatus {
  planId: Long;
  provAddress: string;
  status: string;
}

function createBaseEventCreate(): EventCreate {
  return { planId: Long.UZERO, provAddress: "", bytes: "", duration: "", prices: "", private: false };
}

export const EventCreate: MessageFns<EventCreate> = {
  encode(message: EventCreate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.planId.toString());
    }
    if (message.provAddress !== "") {
      writer.uint32(18).string(message.provAddress);
    }
    if (message.bytes !== "") {
      writer.uint32(26).string(message.bytes);
    }
    if (message.duration !== "") {
      writer.uint32(34).string(message.duration);
    }
    if (message.prices !== "") {
      writer.uint32(42).string(message.prices);
    }
    if (message.private !== false) {
      writer.uint32(48).bool(message.private);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventCreate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventCreate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bytes = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.duration = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.prices = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.private = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventCreate {
    return {
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
      provAddress: isSet(object.provAddress)
        ? globalThis.String(object.provAddress)
        : isSet(object.prov_address)
        ? globalThis.String(object.prov_address)
        : "",
      bytes: isSet(object.bytes) ? globalThis.String(object.bytes) : "",
      duration: isSet(object.duration) ? globalThis.String(object.duration) : "",
      prices: isSet(object.prices) ? globalThis.String(object.prices) : "",
      private: isSet(object.private) ? globalThis.Boolean(object.private) : false,
    };
  },

  toJSON(message: EventCreate): unknown {
    const obj: any = {};
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    if (message.provAddress !== "") {
      obj.provAddress = message.provAddress;
    }
    if (message.bytes !== "") {
      obj.bytes = message.bytes;
    }
    if (message.duration !== "") {
      obj.duration = message.duration;
    }
    if (message.prices !== "") {
      obj.prices = message.prices;
    }
    if (message.private !== false) {
      obj.private = message.private;
    }
    return obj;
  },

  create(base?: DeepPartial<EventCreate>): EventCreate {
    return EventCreate.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventCreate>): EventCreate {
    const message = createBaseEventCreate();
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    message.provAddress = object.provAddress ?? "";
    message.bytes = object.bytes ?? "";
    message.duration = object.duration ?? "";
    message.prices = object.prices ?? "";
    message.private = object.private ?? false;
    return message;
  },
};

function createBaseEventLinkNode(): EventLinkNode {
  return { planId: Long.UZERO, provAddress: "", nodeAddress: "" };
}

export const EventLinkNode: MessageFns<EventLinkNode> = {
  encode(message: EventLinkNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.planId.toString());
    }
    if (message.provAddress !== "") {
      writer.uint32(18).string(message.provAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventLinkNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventLinkNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventLinkNode {
    return {
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
      provAddress: isSet(object.provAddress)
        ? globalThis.String(object.provAddress)
        : isSet(object.prov_address)
        ? globalThis.String(object.prov_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
    };
  },

  toJSON(message: EventLinkNode): unknown {
    const obj: any = {};
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    if (message.provAddress !== "") {
      obj.provAddress = message.provAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    return obj;
  },

  create(base?: DeepPartial<EventLinkNode>): EventLinkNode {
    return EventLinkNode.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventLinkNode>): EventLinkNode {
    const message = createBaseEventLinkNode();
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    message.provAddress = object.provAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    return message;
  },
};

function createBaseEventUnlinkNode(): EventUnlinkNode {
  return { planId: Long.UZERO, provAddress: "", nodeAddress: "" };
}

export const EventUnlinkNode: MessageFns<EventUnlinkNode> = {
  encode(message: EventUnlinkNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.planId.toString());
    }
    if (message.provAddress !== "") {
      writer.uint32(18).string(message.provAddress);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(26).string(message.nodeAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUnlinkNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUnlinkNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUnlinkNode {
    return {
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
      provAddress: isSet(object.provAddress)
        ? globalThis.String(object.provAddress)
        : isSet(object.prov_address)
        ? globalThis.String(object.prov_address)
        : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
    };
  },

  toJSON(message: EventUnlinkNode): unknown {
    const obj: any = {};
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    if (message.provAddress !== "") {
      obj.provAddress = message.provAddress;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUnlinkNode>): EventUnlinkNode {
    return EventUnlinkNode.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUnlinkNode>): EventUnlinkNode {
    const message = createBaseEventUnlinkNode();
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    message.provAddress = object.provAddress ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    return message;
  },
};

function createBaseEventUpdateDetails(): EventUpdateDetails {
  return { planId: Long.UZERO, provAddress: "", private: false };
}

export const EventUpdateDetails: MessageFns<EventUpdateDetails> = {
  encode(message: EventUpdateDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.planId.toString());
    }
    if (message.provAddress !== "") {
      writer.uint32(18).string(message.provAddress);
    }
    if (message.private !== false) {
      writer.uint32(24).bool(message.private);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.private = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateDetails {
    return {
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
      provAddress: isSet(object.provAddress)
        ? globalThis.String(object.provAddress)
        : isSet(object.prov_address)
        ? globalThis.String(object.prov_address)
        : "",
      private: isSet(object.private) ? globalThis.Boolean(object.private) : false,
    };
  },

  toJSON(message: EventUpdateDetails): unknown {
    const obj: any = {};
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    if (message.provAddress !== "") {
      obj.provAddress = message.provAddress;
    }
    if (message.private !== false) {
      obj.private = message.private;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    return EventUpdateDetails.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateDetails>): EventUpdateDetails {
    const message = createBaseEventUpdateDetails();
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    message.provAddress = object.provAddress ?? "";
    message.private = object.private ?? false;
    return message;
  },
};

function createBaseEventUpdateStatus(): EventUpdateStatus {
  return { planId: Long.UZERO, provAddress: "", status: "" };
}

export const EventUpdateStatus: MessageFns<EventUpdateStatus> = {
  encode(message: EventUpdateStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.planId.toString());
    }
    if (message.provAddress !== "") {
      writer.uint32(18).string(message.provAddress);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateStatus {
    return {
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
      provAddress: isSet(object.provAddress)
        ? globalThis.String(object.provAddress)
        : isSet(object.prov_address)
        ? globalThis.String(object.prov_address)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: EventUpdateStatus): unknown {
    const obj: any = {};
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    if (message.provAddress !== "") {
      obj.provAddress = message.provAddress;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    return EventUpdateStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    const message = createBaseEventUpdateStatus();
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    message.provAddress = object.provAddress ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
