// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/swap/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.swap.v1";

export interface Params {
  swapEnabled: boolean;
  swapDenom: string;
  approveBy: string;
}

function createBaseParams(): Params {
  return { swapEnabled: false, swapDenom: "", approveBy: "" };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.swapEnabled !== false) {
      writer.uint32(8).bool(message.swapEnabled);
    }
    if (message.swapDenom !== "") {
      writer.uint32(18).string(message.swapDenom);
    }
    if (message.approveBy !== "") {
      writer.uint32(26).string(message.approveBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.swapEnabled = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.swapDenom = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.approveBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      swapEnabled: isSet(object.swapEnabled)
        ? globalThis.Boolean(object.swapEnabled)
        : isSet(object.swap_enabled)
        ? globalThis.Boolean(object.swap_enabled)
        : false,
      swapDenom: isSet(object.swapDenom)
        ? globalThis.String(object.swapDenom)
        : isSet(object.swap_denom)
        ? globalThis.String(object.swap_denom)
        : "",
      approveBy: isSet(object.approveBy)
        ? globalThis.String(object.approveBy)
        : isSet(object.approve_by)
        ? globalThis.String(object.approve_by)
        : "",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.swapEnabled !== false) {
      obj.swapEnabled = message.swapEnabled;
    }
    if (message.swapDenom !== "") {
      obj.swapDenom = message.swapDenom;
    }
    if (message.approveBy !== "") {
      obj.approveBy = message.approveBy;
    }
    return obj;
  },

  create(base?: DeepPartial<Params>): Params {
    return Params.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Params>): Params {
    const message = createBaseParams();
    message.swapEnabled = object.swapEnabled ?? false;
    message.swapDenom = object.swapDenom ?? "";
    message.approveBy = object.approveBy ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
