// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/lease/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.lease.v1";

export interface Params {
  maxHours: Long;
  minHours: Long;
  stakingShare: string;
}

function createBaseParams(): Params {
  return { maxHours: Long.ZERO, minHours: Long.ZERO, stakingShare: "" };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.maxHours.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.maxHours.toString());
    }
    if (!message.minHours.equals(Long.ZERO)) {
      writer.uint32(16).int64(message.minHours.toString());
    }
    if (message.stakingShare !== "") {
      writer.uint32(26).string(message.stakingShare);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxHours = Long.fromString(reader.int64().toString());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minHours = Long.fromString(reader.int64().toString());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stakingShare = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxHours: isSet(object.maxHours)
        ? Long.fromValue(object.maxHours)
        : isSet(object.max_hours)
        ? Long.fromValue(object.max_hours)
        : Long.ZERO,
      minHours: isSet(object.minHours)
        ? Long.fromValue(object.minHours)
        : isSet(object.min_hours)
        ? Long.fromValue(object.min_hours)
        : Long.ZERO,
      stakingShare: isSet(object.stakingShare)
        ? globalThis.String(object.stakingShare)
        : isSet(object.staking_share)
        ? globalThis.String(object.staking_share)
        : "",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (!message.maxHours.equals(Long.ZERO)) {
      obj.maxHours = (message.maxHours || Long.ZERO).toString();
    }
    if (!message.minHours.equals(Long.ZERO)) {
      obj.minHours = (message.minHours || Long.ZERO).toString();
    }
    if (message.stakingShare !== "") {
      obj.stakingShare = message.stakingShare;
    }
    return obj;
  },

  create(base?: DeepPartial<Params>): Params {
    return Params.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Params>): Params {
    const message = createBaseParams();
    message.maxHours = (object.maxHours !== undefined && object.maxHours !== null)
      ? Long.fromValue(object.maxHours)
      : Long.ZERO;
    message.minHours = (object.minHours !== undefined && object.minHours !== null)
      ? Long.fromValue(object.minHours)
      : Long.ZERO;
    message.stakingShare = object.stakingShare ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
