// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: sentinel/subscription/v3/params.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Duration } from "../../../google/protobuf/duration";

export const protobufPackage = "sentinel.subscription.v3";

export interface Params {
  maxAllocations: Long;
  stakingShare: string;
  statusTimeout?: Duration | undefined;
}

function createBaseParams(): Params {
  return { maxAllocations: Long.ZERO, stakingShare: "", statusTimeout: undefined };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (!message.maxAllocations.equals(Long.ZERO)) {
      writer.uint32(8).int64(message.maxAllocations);
    }
    if (message.stakingShare !== "") {
      writer.uint32(18).string(message.stakingShare);
    }
    if (message.statusTimeout !== undefined) {
      Duration.encode(message.statusTimeout, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.maxAllocations = reader.int64() as Long;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.stakingShare = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.statusTimeout = Duration.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxAllocations: isSet(object.maxAllocations) ? Long.fromValue(object.maxAllocations) : Long.ZERO,
      stakingShare: isSet(object.stakingShare) ? globalThis.String(object.stakingShare) : "",
      statusTimeout: isSet(object.statusTimeout) ? Duration.fromJSON(object.statusTimeout) : undefined,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (!message.maxAllocations.equals(Long.ZERO)) {
      obj.maxAllocations = (message.maxAllocations || Long.ZERO).toString();
    }
    if (message.stakingShare !== "") {
      obj.stakingShare = message.stakingShare;
    }
    if (message.statusTimeout !== undefined) {
      obj.statusTimeout = Duration.toJSON(message.statusTimeout);
    }
    return obj;
  },

  create(base?: DeepPartial<Params>): Params {
    return Params.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Params>): Params {
    const message = createBaseParams();
    message.maxAllocations = (object.maxAllocations !== undefined && object.maxAllocations !== null)
      ? Long.fromValue(object.maxAllocations)
      : Long.ZERO;
    message.stakingShare = object.stakingShare ?? "";
    message.statusTimeout = (object.statusTimeout !== undefined && object.statusTimeout !== null)
      ? Duration.fromPartial(object.statusTimeout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
