// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/subscription/v3/session.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { BaseSession } from "../../session/v3/session";

export const protobufPackage = "sentinel.subscription.v3";

export interface Session {
  baseSession?: BaseSession | undefined;
  subscriptionId: Long;
}

function createBaseSession(): Session {
  return { baseSession: undefined, subscriptionId: Long.UZERO };
}

export const Session: MessageFns<Session> = {
  encode(message: Session, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baseSession !== undefined) {
      BaseSession.encode(message.baseSession, writer.uint32(10).fork()).join();
    }
    if (!message.subscriptionId.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.subscriptionId.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baseSession = BaseSession.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.subscriptionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      baseSession: isSet(object.baseSession)
        ? BaseSession.fromJSON(object.baseSession)
        : isSet(object.base_session)
        ? BaseSession.fromJSON(object.base_session)
        : undefined,
      subscriptionId: isSet(object.subscriptionId)
        ? Long.fromValue(object.subscriptionId)
        : isSet(object.subscription_id)
        ? Long.fromValue(object.subscription_id)
        : Long.UZERO,
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.baseSession !== undefined) {
      obj.baseSession = BaseSession.toJSON(message.baseSession);
    }
    if (!message.subscriptionId.equals(Long.UZERO)) {
      obj.subscriptionId = (message.subscriptionId || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<Session>): Session {
    return Session.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Session>): Session {
    const message = createBaseSession();
    message.baseSession = (object.baseSession !== undefined && object.baseSession !== null)
      ? BaseSession.fromPartial(object.baseSession)
      : undefined;
    message.subscriptionId = (object.subscriptionId !== undefined && object.subscriptionId !== null)
      ? Long.fromValue(object.subscriptionId)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
