// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: sentinel/oracle/v1/asset.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { SpotPriceRequest } from "../../../osmosis/poolmanager/v1beta1/query";
import { QueryGetProtoRevPoolRequest } from "../../../osmosis/protorev/v1beta1/query";

export const protobufPackage = "sentinel.oracle.v1";

export interface Asset {
  denom: string;
  decimals: Long;
  protoRevPoolRequest?: QueryGetProtoRevPoolRequest | undefined;
  spotPriceRequest?: SpotPriceRequest | undefined;
  spotPrice: string;
  spotPriceHeight: Long;
}

function createBaseAsset(): Asset {
  return {
    denom: "",
    decimals: Long.ZERO,
    protoRevPoolRequest: undefined,
    spotPriceRequest: undefined,
    spotPrice: "",
    spotPriceHeight: Long.ZERO,
  };
}

export const Asset = {
  encode(message: Asset, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.denom !== "") {
      writer.uint32(10).string(message.denom);
    }
    if (!message.decimals.equals(Long.ZERO)) {
      writer.uint32(16).int64(message.decimals);
    }
    if (message.protoRevPoolRequest !== undefined) {
      QueryGetProtoRevPoolRequest.encode(message.protoRevPoolRequest, writer.uint32(26).fork()).ldelim();
    }
    if (message.spotPriceRequest !== undefined) {
      SpotPriceRequest.encode(message.spotPriceRequest, writer.uint32(34).fork()).ldelim();
    }
    if (message.spotPrice !== "") {
      writer.uint32(42).string(message.spotPrice);
    }
    if (!message.spotPriceHeight.equals(Long.ZERO)) {
      writer.uint32(48).int64(message.spotPriceHeight);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Asset {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.denom = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.decimals = reader.int64() as Long;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.protoRevPoolRequest = QueryGetProtoRevPoolRequest.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.spotPriceRequest = SpotPriceRequest.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.spotPrice = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.spotPriceHeight = reader.int64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Asset {
    return {
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      decimals: isSet(object.decimals) ? Long.fromValue(object.decimals) : Long.ZERO,
      protoRevPoolRequest: isSet(object.protoRevPoolRequest)
        ? QueryGetProtoRevPoolRequest.fromJSON(object.protoRevPoolRequest)
        : undefined,
      spotPriceRequest: isSet(object.spotPriceRequest) ? SpotPriceRequest.fromJSON(object.spotPriceRequest) : undefined,
      spotPrice: isSet(object.spotPrice) ? globalThis.String(object.spotPrice) : "",
      spotPriceHeight: isSet(object.spotPriceHeight) ? Long.fromValue(object.spotPriceHeight) : Long.ZERO,
    };
  },

  toJSON(message: Asset): unknown {
    const obj: any = {};
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (!message.decimals.equals(Long.ZERO)) {
      obj.decimals = (message.decimals || Long.ZERO).toString();
    }
    if (message.protoRevPoolRequest !== undefined) {
      obj.protoRevPoolRequest = QueryGetProtoRevPoolRequest.toJSON(message.protoRevPoolRequest);
    }
    if (message.spotPriceRequest !== undefined) {
      obj.spotPriceRequest = SpotPriceRequest.toJSON(message.spotPriceRequest);
    }
    if (message.spotPrice !== "") {
      obj.spotPrice = message.spotPrice;
    }
    if (!message.spotPriceHeight.equals(Long.ZERO)) {
      obj.spotPriceHeight = (message.spotPriceHeight || Long.ZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<Asset>): Asset {
    return Asset.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Asset>): Asset {
    const message = createBaseAsset();
    message.denom = object.denom ?? "";
    message.decimals = (object.decimals !== undefined && object.decimals !== null)
      ? Long.fromValue(object.decimals)
      : Long.ZERO;
    message.protoRevPoolRequest = (object.protoRevPoolRequest !== undefined && object.protoRevPoolRequest !== null)
      ? QueryGetProtoRevPoolRequest.fromPartial(object.protoRevPoolRequest)
      : undefined;
    message.spotPriceRequest = (object.spotPriceRequest !== undefined && object.spotPriceRequest !== null)
      ? SpotPriceRequest.fromPartial(object.spotPriceRequest)
      : undefined;
    message.spotPrice = object.spotPrice ?? "";
    message.spotPriceHeight = (object.spotPriceHeight !== undefined && object.spotPriceHeight !== null)
      ? Long.fromValue(object.spotPriceHeight)
      : Long.ZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
