// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/oracle/v1/msg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { SpotPriceRequest } from "../../../osmosis/poolmanager/v1beta1/query";
import { QueryGetProtoRevPoolRequest } from "../../../osmosis/protorev/v1beta1/query";
import { Params } from "./params";

export const protobufPackage = "sentinel.oracle.v1";

export interface MsgCreateAssetRequest {
  from: string;
  denom: string;
  decimals: Long;
  protoRevPoolRequest?: QueryGetProtoRevPoolRequest | undefined;
  spotPriceRequest?: SpotPriceRequest | undefined;
}

export interface MsgDeleteAssetRequest {
  from: string;
  denom: string;
}

export interface MsgUpdateAssetRequest {
  from: string;
  denom: string;
  decimals: Long;
  protoRevPoolRequest?: QueryGetProtoRevPoolRequest | undefined;
  spotPriceRequest?: SpotPriceRequest | undefined;
}

export interface MsgUpdateParamsRequest {
  from: string;
  params?: Params | undefined;
}

export interface MsgCreateAssetResponse {
}

export interface MsgDeleteAssetResponse {
}

export interface MsgUpdateAssetResponse {
}

export interface MsgUpdateParamsResponse {
}

function createBaseMsgCreateAssetRequest(): MsgCreateAssetRequest {
  return { from: "", denom: "", decimals: Long.ZERO, protoRevPoolRequest: undefined, spotPriceRequest: undefined };
}

export const MsgCreateAssetRequest: MessageFns<MsgCreateAssetRequest> = {
  encode(message: MsgCreateAssetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.denom !== "") {
      writer.uint32(18).string(message.denom);
    }
    if (!message.decimals.equals(Long.ZERO)) {
      writer.uint32(24).int64(message.decimals.toString());
    }
    if (message.protoRevPoolRequest !== undefined) {
      QueryGetProtoRevPoolRequest.encode(message.protoRevPoolRequest, writer.uint32(34).fork()).join();
    }
    if (message.spotPriceRequest !== undefined) {
      SpotPriceRequest.encode(message.spotPriceRequest, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateAssetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateAssetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.denom = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.decimals = Long.fromString(reader.int64().toString());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.protoRevPoolRequest = QueryGetProtoRevPoolRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.spotPriceRequest = SpotPriceRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateAssetRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      decimals: isSet(object.decimals) ? Long.fromValue(object.decimals) : Long.ZERO,
      protoRevPoolRequest: isSet(object.protoRevPoolRequest)
        ? QueryGetProtoRevPoolRequest.fromJSON(object.protoRevPoolRequest)
        : isSet(object.proto_rev_pool_request)
        ? QueryGetProtoRevPoolRequest.fromJSON(object.proto_rev_pool_request)
        : undefined,
      spotPriceRequest: isSet(object.spotPriceRequest)
        ? SpotPriceRequest.fromJSON(object.spotPriceRequest)
        : isSet(object.spot_price_request)
        ? SpotPriceRequest.fromJSON(object.spot_price_request)
        : undefined,
    };
  },

  toJSON(message: MsgCreateAssetRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (!message.decimals.equals(Long.ZERO)) {
      obj.decimals = (message.decimals || Long.ZERO).toString();
    }
    if (message.protoRevPoolRequest !== undefined) {
      obj.protoRevPoolRequest = QueryGetProtoRevPoolRequest.toJSON(message.protoRevPoolRequest);
    }
    if (message.spotPriceRequest !== undefined) {
      obj.spotPriceRequest = SpotPriceRequest.toJSON(message.spotPriceRequest);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgCreateAssetRequest>): MsgCreateAssetRequest {
    return MsgCreateAssetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgCreateAssetRequest>): MsgCreateAssetRequest {
    const message = createBaseMsgCreateAssetRequest();
    message.from = object.from ?? "";
    message.denom = object.denom ?? "";
    message.decimals = (object.decimals !== undefined && object.decimals !== null)
      ? Long.fromValue(object.decimals)
      : Long.ZERO;
    message.protoRevPoolRequest = (object.protoRevPoolRequest !== undefined && object.protoRevPoolRequest !== null)
      ? QueryGetProtoRevPoolRequest.fromPartial(object.protoRevPoolRequest)
      : undefined;
    message.spotPriceRequest = (object.spotPriceRequest !== undefined && object.spotPriceRequest !== null)
      ? SpotPriceRequest.fromPartial(object.spotPriceRequest)
      : undefined;
    return message;
  },
};

function createBaseMsgDeleteAssetRequest(): MsgDeleteAssetRequest {
  return { from: "", denom: "" };
}

export const MsgDeleteAssetRequest: MessageFns<MsgDeleteAssetRequest> = {
  encode(message: MsgDeleteAssetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.denom !== "") {
      writer.uint32(18).string(message.denom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteAssetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteAssetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.denom = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDeleteAssetRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
    };
  },

  toJSON(message: MsgDeleteAssetRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgDeleteAssetRequest>): MsgDeleteAssetRequest {
    return MsgDeleteAssetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgDeleteAssetRequest>): MsgDeleteAssetRequest {
    const message = createBaseMsgDeleteAssetRequest();
    message.from = object.from ?? "";
    message.denom = object.denom ?? "";
    return message;
  },
};

function createBaseMsgUpdateAssetRequest(): MsgUpdateAssetRequest {
  return { from: "", denom: "", decimals: Long.ZERO, protoRevPoolRequest: undefined, spotPriceRequest: undefined };
}

export const MsgUpdateAssetRequest: MessageFns<MsgUpdateAssetRequest> = {
  encode(message: MsgUpdateAssetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.denom !== "") {
      writer.uint32(18).string(message.denom);
    }
    if (!message.decimals.equals(Long.ZERO)) {
      writer.uint32(24).int64(message.decimals.toString());
    }
    if (message.protoRevPoolRequest !== undefined) {
      QueryGetProtoRevPoolRequest.encode(message.protoRevPoolRequest, writer.uint32(34).fork()).join();
    }
    if (message.spotPriceRequest !== undefined) {
      SpotPriceRequest.encode(message.spotPriceRequest, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateAssetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateAssetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.denom = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.decimals = Long.fromString(reader.int64().toString());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.protoRevPoolRequest = QueryGetProtoRevPoolRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.spotPriceRequest = SpotPriceRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateAssetRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      decimals: isSet(object.decimals) ? Long.fromValue(object.decimals) : Long.ZERO,
      protoRevPoolRequest: isSet(object.protoRevPoolRequest)
        ? QueryGetProtoRevPoolRequest.fromJSON(object.protoRevPoolRequest)
        : isSet(object.proto_rev_pool_request)
        ? QueryGetProtoRevPoolRequest.fromJSON(object.proto_rev_pool_request)
        : undefined,
      spotPriceRequest: isSet(object.spotPriceRequest)
        ? SpotPriceRequest.fromJSON(object.spotPriceRequest)
        : isSet(object.spot_price_request)
        ? SpotPriceRequest.fromJSON(object.spot_price_request)
        : undefined,
    };
  },

  toJSON(message: MsgUpdateAssetRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (!message.decimals.equals(Long.ZERO)) {
      obj.decimals = (message.decimals || Long.ZERO).toString();
    }
    if (message.protoRevPoolRequest !== undefined) {
      obj.protoRevPoolRequest = QueryGetProtoRevPoolRequest.toJSON(message.protoRevPoolRequest);
    }
    if (message.spotPriceRequest !== undefined) {
      obj.spotPriceRequest = SpotPriceRequest.toJSON(message.spotPriceRequest);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgUpdateAssetRequest>): MsgUpdateAssetRequest {
    return MsgUpdateAssetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgUpdateAssetRequest>): MsgUpdateAssetRequest {
    const message = createBaseMsgUpdateAssetRequest();
    message.from = object.from ?? "";
    message.denom = object.denom ?? "";
    message.decimals = (object.decimals !== undefined && object.decimals !== null)
      ? Long.fromValue(object.decimals)
      : Long.ZERO;
    message.protoRevPoolRequest = (object.protoRevPoolRequest !== undefined && object.protoRevPoolRequest !== null)
      ? QueryGetProtoRevPoolRequest.fromPartial(object.protoRevPoolRequest)
      : undefined;
    message.spotPriceRequest = (object.spotPriceRequest !== undefined && object.spotPriceRequest !== null)
      ? SpotPriceRequest.fromPartial(object.spotPriceRequest)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsRequest(): MsgUpdateParamsRequest {
  return { from: "", params: undefined };
}

export const MsgUpdateParamsRequest: MessageFns<MsgUpdateParamsRequest> = {
  encode(message: MsgUpdateParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParamsRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParamsRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgUpdateParamsRequest>): MsgUpdateParamsRequest {
    return MsgUpdateParamsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgUpdateParamsRequest>): MsgUpdateParamsRequest {
    const message = createBaseMsgUpdateParamsRequest();
    message.from = object.from ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgCreateAssetResponse(): MsgCreateAssetResponse {
  return {};
}

export const MsgCreateAssetResponse: MessageFns<MsgCreateAssetResponse> = {
  encode(_: MsgCreateAssetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateAssetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateAssetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCreateAssetResponse {
    return {};
  },

  toJSON(_: MsgCreateAssetResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgCreateAssetResponse>): MsgCreateAssetResponse {
    return MsgCreateAssetResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgCreateAssetResponse>): MsgCreateAssetResponse {
    const message = createBaseMsgCreateAssetResponse();
    return message;
  },
};

function createBaseMsgDeleteAssetResponse(): MsgDeleteAssetResponse {
  return {};
}

export const MsgDeleteAssetResponse: MessageFns<MsgDeleteAssetResponse> = {
  encode(_: MsgDeleteAssetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteAssetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteAssetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDeleteAssetResponse {
    return {};
  },

  toJSON(_: MsgDeleteAssetResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgDeleteAssetResponse>): MsgDeleteAssetResponse {
    return MsgDeleteAssetResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgDeleteAssetResponse>): MsgDeleteAssetResponse {
    const message = createBaseMsgDeleteAssetResponse();
    return message;
  },
};

function createBaseMsgUpdateAssetResponse(): MsgUpdateAssetResponse {
  return {};
}

export const MsgUpdateAssetResponse: MessageFns<MsgUpdateAssetResponse> = {
  encode(_: MsgUpdateAssetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateAssetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateAssetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateAssetResponse {
    return {};
  },

  toJSON(_: MsgUpdateAssetResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgUpdateAssetResponse>): MsgUpdateAssetResponse {
    return MsgUpdateAssetResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgUpdateAssetResponse>): MsgUpdateAssetResponse {
    const message = createBaseMsgUpdateAssetResponse();
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgUpdateParamsResponse>): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgUpdateParamsResponse>): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

export interface MsgService {
  MsgCreateAsset(request: MsgCreateAssetRequest): Promise<MsgCreateAssetResponse>;
  MsgDeleteAsset(request: MsgDeleteAssetRequest): Promise<MsgDeleteAssetResponse>;
  MsgUpdateAsset(request: MsgUpdateAssetRequest): Promise<MsgUpdateAssetResponse>;
  MsgUpdateParams(request: MsgUpdateParamsRequest): Promise<MsgUpdateParamsResponse>;
}

export const MsgServiceServiceName = "sentinel.oracle.v1.MsgService";
export class MsgServiceClientImpl implements MsgService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceServiceName;
    this.rpc = rpc;
    this.MsgCreateAsset = this.MsgCreateAsset.bind(this);
    this.MsgDeleteAsset = this.MsgDeleteAsset.bind(this);
    this.MsgUpdateAsset = this.MsgUpdateAsset.bind(this);
    this.MsgUpdateParams = this.MsgUpdateParams.bind(this);
  }
  MsgCreateAsset(request: MsgCreateAssetRequest): Promise<MsgCreateAssetResponse> {
    const data = MsgCreateAssetRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgCreateAsset", data);
    return promise.then((data) => MsgCreateAssetResponse.decode(new BinaryReader(data)));
  }

  MsgDeleteAsset(request: MsgDeleteAssetRequest): Promise<MsgDeleteAssetResponse> {
    const data = MsgDeleteAssetRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgDeleteAsset", data);
    return promise.then((data) => MsgDeleteAssetResponse.decode(new BinaryReader(data)));
  }

  MsgUpdateAsset(request: MsgUpdateAssetRequest): Promise<MsgUpdateAssetResponse> {
    const data = MsgUpdateAssetRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgUpdateAsset", data);
    return promise.then((data) => MsgUpdateAssetResponse.decode(new BinaryReader(data)));
  }

  MsgUpdateParams(request: MsgUpdateParamsRequest): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgUpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
