// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/subscription/v2/allocation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.subscription.v2";

export interface Allocation {
  id: Long;
  address: string;
  grantedBytes: string;
  utilisedBytes: string;
}

function createBaseAllocation(): Allocation {
  return { id: Long.UZERO, address: "", grantedBytes: "", utilisedBytes: "" };
}

export const Allocation: MessageFns<Allocation> = {
  encode(message: Allocation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.id.toString());
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.grantedBytes !== "") {
      writer.uint32(26).string(message.grantedBytes);
    }
    if (message.utilisedBytes !== "") {
      writer.uint32(34).string(message.utilisedBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Allocation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAllocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.grantedBytes = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.utilisedBytes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Allocation {
    return {
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      grantedBytes: isSet(object.grantedBytes)
        ? globalThis.String(object.grantedBytes)
        : isSet(object.granted_bytes)
        ? globalThis.String(object.granted_bytes)
        : "",
      utilisedBytes: isSet(object.utilisedBytes)
        ? globalThis.String(object.utilisedBytes)
        : isSet(object.utilised_bytes)
        ? globalThis.String(object.utilised_bytes)
        : "",
    };
  },

  toJSON(message: Allocation): unknown {
    const obj: any = {};
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.grantedBytes !== "") {
      obj.grantedBytes = message.grantedBytes;
    }
    if (message.utilisedBytes !== "") {
      obj.utilisedBytes = message.utilisedBytes;
    }
    return obj;
  },

  create(base?: DeepPartial<Allocation>): Allocation {
    return Allocation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Allocation>): Allocation {
    const message = createBaseAllocation();
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.address = object.address ?? "";
    message.grantedBytes = object.grantedBytes ?? "";
    message.utilisedBytes = object.utilisedBytes ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
