// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/subscription/v2/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";
import { Status, statusFromJSON, statusToJSON } from "../../types/v1/status";

export const protobufPackage = "sentinel.subscription.v2";

export interface EventAllocate {
  address: string;
  grantedBytes: string;
  utilisedBytes: string;
  id: Long;
}

export interface EventCreatePayout {
  address: string;
  nodeAddress: string;
  id: Long;
}

export interface EventPayForPayout {
  address: string;
  nodeAddress: string;
  payment: string;
  stakingReward: string;
  id: Long;
}

export interface EventPayForPlan {
  address: string;
  payment: string;
  providerAddress: string;
  stakingReward: string;
  id: Long;
}

export interface EventPayForSession {
  address: string;
  nodeAddress: string;
  payment: string;
  stakingReward: string;
  sessionId: Long;
  subscriptionId: Long;
}

export interface EventRefund {
  address: string;
  amount: string;
  id: Long;
}

export interface EventUpdateStatus {
  status: Status;
  address: string;
  id: Long;
  planId: Long;
}

function createBaseEventAllocate(): EventAllocate {
  return { address: "", grantedBytes: "", utilisedBytes: "", id: Long.UZERO };
}

export const EventAllocate: MessageFns<EventAllocate> = {
  encode(message: EventAllocate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.grantedBytes !== "") {
      writer.uint32(18).string(message.grantedBytes);
    }
    if (message.utilisedBytes !== "") {
      writer.uint32(26).string(message.utilisedBytes);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventAllocate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventAllocate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.grantedBytes = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.utilisedBytes = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventAllocate {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      grantedBytes: isSet(object.grantedBytes)
        ? globalThis.String(object.grantedBytes)
        : isSet(object.granted_bytes)
        ? globalThis.String(object.granted_bytes)
        : "",
      utilisedBytes: isSet(object.utilisedBytes)
        ? globalThis.String(object.utilisedBytes)
        : isSet(object.utilised_bytes)
        ? globalThis.String(object.utilised_bytes)
        : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: EventAllocate): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.grantedBytes !== "") {
      obj.grantedBytes = message.grantedBytes;
    }
    if (message.utilisedBytes !== "") {
      obj.utilisedBytes = message.utilisedBytes;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventAllocate>): EventAllocate {
    return EventAllocate.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventAllocate>): EventAllocate {
    const message = createBaseEventAllocate();
    message.address = object.address ?? "";
    message.grantedBytes = object.grantedBytes ?? "";
    message.utilisedBytes = object.utilisedBytes ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseEventCreatePayout(): EventCreatePayout {
  return { address: "", nodeAddress: "", id: Long.UZERO };
}

export const EventCreatePayout: MessageFns<EventCreatePayout> = {
  encode(message: EventCreatePayout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(18).string(message.nodeAddress);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventCreatePayout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventCreatePayout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventCreatePayout {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: EventCreatePayout): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventCreatePayout>): EventCreatePayout {
    return EventCreatePayout.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventCreatePayout>): EventCreatePayout {
    const message = createBaseEventCreatePayout();
    message.address = object.address ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseEventPayForPayout(): EventPayForPayout {
  return { address: "", nodeAddress: "", payment: "", stakingReward: "", id: Long.UZERO };
}

export const EventPayForPayout: MessageFns<EventPayForPayout> = {
  encode(message: EventPayForPayout, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(18).string(message.nodeAddress);
    }
    if (message.payment !== "") {
      writer.uint32(26).string(message.payment);
    }
    if (message.stakingReward !== "") {
      writer.uint32(34).string(message.stakingReward);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(40).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventPayForPayout {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventPayForPayout();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payment = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stakingReward = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventPayForPayout {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      payment: isSet(object.payment) ? globalThis.String(object.payment) : "",
      stakingReward: isSet(object.stakingReward)
        ? globalThis.String(object.stakingReward)
        : isSet(object.staking_reward)
        ? globalThis.String(object.staking_reward)
        : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: EventPayForPayout): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.payment !== "") {
      obj.payment = message.payment;
    }
    if (message.stakingReward !== "") {
      obj.stakingReward = message.stakingReward;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventPayForPayout>): EventPayForPayout {
    return EventPayForPayout.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventPayForPayout>): EventPayForPayout {
    const message = createBaseEventPayForPayout();
    message.address = object.address ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.payment = object.payment ?? "";
    message.stakingReward = object.stakingReward ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseEventPayForPlan(): EventPayForPlan {
  return { address: "", payment: "", providerAddress: "", stakingReward: "", id: Long.UZERO };
}

export const EventPayForPlan: MessageFns<EventPayForPlan> = {
  encode(message: EventPayForPlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.payment !== "") {
      writer.uint32(18).string(message.payment);
    }
    if (message.providerAddress !== "") {
      writer.uint32(26).string(message.providerAddress);
    }
    if (message.stakingReward !== "") {
      writer.uint32(34).string(message.stakingReward);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(40).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventPayForPlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventPayForPlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payment = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.providerAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stakingReward = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventPayForPlan {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      payment: isSet(object.payment) ? globalThis.String(object.payment) : "",
      providerAddress: isSet(object.providerAddress)
        ? globalThis.String(object.providerAddress)
        : isSet(object.provider_address)
        ? globalThis.String(object.provider_address)
        : "",
      stakingReward: isSet(object.stakingReward)
        ? globalThis.String(object.stakingReward)
        : isSet(object.staking_reward)
        ? globalThis.String(object.staking_reward)
        : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: EventPayForPlan): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.payment !== "") {
      obj.payment = message.payment;
    }
    if (message.providerAddress !== "") {
      obj.providerAddress = message.providerAddress;
    }
    if (message.stakingReward !== "") {
      obj.stakingReward = message.stakingReward;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventPayForPlan>): EventPayForPlan {
    return EventPayForPlan.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventPayForPlan>): EventPayForPlan {
    const message = createBaseEventPayForPlan();
    message.address = object.address ?? "";
    message.payment = object.payment ?? "";
    message.providerAddress = object.providerAddress ?? "";
    message.stakingReward = object.stakingReward ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseEventPayForSession(): EventPayForSession {
  return {
    address: "",
    nodeAddress: "",
    payment: "",
    stakingReward: "",
    sessionId: Long.UZERO,
    subscriptionId: Long.UZERO,
  };
}

export const EventPayForSession: MessageFns<EventPayForSession> = {
  encode(message: EventPayForSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.nodeAddress !== "") {
      writer.uint32(18).string(message.nodeAddress);
    }
    if (message.payment !== "") {
      writer.uint32(26).string(message.payment);
    }
    if (message.stakingReward !== "") {
      writer.uint32(34).string(message.stakingReward);
    }
    if (!message.sessionId.equals(Long.UZERO)) {
      writer.uint32(40).uint64(message.sessionId.toString());
    }
    if (!message.subscriptionId.equals(Long.UZERO)) {
      writer.uint32(48).uint64(message.subscriptionId.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventPayForSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventPayForSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payment = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stakingReward = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sessionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.subscriptionId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventPayForSession {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      nodeAddress: isSet(object.nodeAddress)
        ? globalThis.String(object.nodeAddress)
        : isSet(object.node_address)
        ? globalThis.String(object.node_address)
        : "",
      payment: isSet(object.payment) ? globalThis.String(object.payment) : "",
      stakingReward: isSet(object.stakingReward)
        ? globalThis.String(object.stakingReward)
        : isSet(object.staking_reward)
        ? globalThis.String(object.staking_reward)
        : "",
      sessionId: isSet(object.sessionId)
        ? Long.fromValue(object.sessionId)
        : isSet(object.session_id)
        ? Long.fromValue(object.session_id)
        : Long.UZERO,
      subscriptionId: isSet(object.subscriptionId)
        ? Long.fromValue(object.subscriptionId)
        : isSet(object.subscription_id)
        ? Long.fromValue(object.subscription_id)
        : Long.UZERO,
    };
  },

  toJSON(message: EventPayForSession): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.nodeAddress !== "") {
      obj.nodeAddress = message.nodeAddress;
    }
    if (message.payment !== "") {
      obj.payment = message.payment;
    }
    if (message.stakingReward !== "") {
      obj.stakingReward = message.stakingReward;
    }
    if (!message.sessionId.equals(Long.UZERO)) {
      obj.sessionId = (message.sessionId || Long.UZERO).toString();
    }
    if (!message.subscriptionId.equals(Long.UZERO)) {
      obj.subscriptionId = (message.subscriptionId || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventPayForSession>): EventPayForSession {
    return EventPayForSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventPayForSession>): EventPayForSession {
    const message = createBaseEventPayForSession();
    message.address = object.address ?? "";
    message.nodeAddress = object.nodeAddress ?? "";
    message.payment = object.payment ?? "";
    message.stakingReward = object.stakingReward ?? "";
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Long.fromValue(object.sessionId)
      : Long.UZERO;
    message.subscriptionId = (object.subscriptionId !== undefined && object.subscriptionId !== null)
      ? Long.fromValue(object.subscriptionId)
      : Long.UZERO;
    return message;
  },
};

function createBaseEventRefund(): EventRefund {
  return { address: "", amount: "", id: Long.UZERO };
}

export const EventRefund: MessageFns<EventRefund> = {
  encode(message: EventRefund, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventRefund {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventRefund();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventRefund {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: EventRefund): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventRefund>): EventRefund {
    return EventRefund.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventRefund>): EventRefund {
    const message = createBaseEventRefund();
    message.address = object.address ?? "";
    message.amount = object.amount ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseEventUpdateStatus(): EventUpdateStatus {
  return { status: 0, address: "", id: Long.UZERO, planId: Long.UZERO };
}

export const EventUpdateStatus: MessageFns<EventUpdateStatus> = {
  encode(message: EventUpdateStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.id.toString());
    }
    if (!message.planId.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.planId.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.planId = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateStatus {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
      planId: isSet(object.planId)
        ? Long.fromValue(object.planId)
        : isSet(object.plan_id)
        ? Long.fromValue(object.plan_id)
        : Long.UZERO,
    };
  },

  toJSON(message: EventUpdateStatus): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    if (!message.planId.equals(Long.UZERO)) {
      obj.planId = (message.planId || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    return EventUpdateStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EventUpdateStatus>): EventUpdateStatus {
    const message = createBaseEventUpdateStatus();
    message.status = object.status ?? 0;
    message.address = object.address ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.planId = (object.planId !== undefined && object.planId !== null)
      ? Long.fromValue(object.planId)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
