// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: sentinel/subscription/v2/msg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "sentinel.subscription.v2";

export interface MsgAllocateRequest {
  from: string;
  id: Long;
  address: string;
  bytes: string;
}

export interface MsgCancelRequest {
  from: string;
  id: Long;
}

export interface MsgAllocateResponse {
}

export interface MsgCancelResponse {
}

function createBaseMsgAllocateRequest(): MsgAllocateRequest {
  return { from: "", id: Long.UZERO, address: "", bytes: "" };
}

export const MsgAllocateRequest: MessageFns<MsgAllocateRequest> = {
  encode(message: MsgAllocateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.id.toString());
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.bytes !== "") {
      writer.uint32(34).string(message.bytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAllocateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAllocateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bytes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAllocateRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      bytes: isSet(object.bytes) ? globalThis.String(object.bytes) : "",
    };
  },

  toJSON(message: MsgAllocateRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.bytes !== "") {
      obj.bytes = message.bytes;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgAllocateRequest>): MsgAllocateRequest {
    return MsgAllocateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgAllocateRequest>): MsgAllocateRequest {
    const message = createBaseMsgAllocateRequest();
    message.from = object.from ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.address = object.address ?? "";
    message.bytes = object.bytes ?? "";
    return message;
  },
};

function createBaseMsgCancelRequest(): MsgCancelRequest {
  return { from: "", id: Long.UZERO };
}

export const MsgCancelRequest: MessageFns<MsgCancelRequest> = {
  encode(message: MsgCancelRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.id.toString());
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCancelRequest {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
    };
  },

  toJSON(message: MsgCancelRequest): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    return obj;
  },

  create(base?: DeepPartial<MsgCancelRequest>): MsgCancelRequest {
    return MsgCancelRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgCancelRequest>): MsgCancelRequest {
    const message = createBaseMsgCancelRequest();
    message.from = object.from ?? "";
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    return message;
  },
};

function createBaseMsgAllocateResponse(): MsgAllocateResponse {
  return {};
}

export const MsgAllocateResponse: MessageFns<MsgAllocateResponse> = {
  encode(_: MsgAllocateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAllocateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAllocateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgAllocateResponse {
    return {};
  },

  toJSON(_: MsgAllocateResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgAllocateResponse>): MsgAllocateResponse {
    return MsgAllocateResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgAllocateResponse>): MsgAllocateResponse {
    const message = createBaseMsgAllocateResponse();
    return message;
  },
};

function createBaseMsgCancelResponse(): MsgCancelResponse {
  return {};
}

export const MsgCancelResponse: MessageFns<MsgCancelResponse> = {
  encode(_: MsgCancelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCancelResponse {
    return {};
  },

  toJSON(_: MsgCancelResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgCancelResponse>): MsgCancelResponse {
    return MsgCancelResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgCancelResponse>): MsgCancelResponse {
    const message = createBaseMsgCancelResponse();
    return message;
  },
};

export interface MsgService {
  MsgAllocate(request: MsgAllocateRequest): Promise<MsgAllocateResponse>;
  MsgCancel(request: MsgCancelRequest): Promise<MsgCancelResponse>;
}

export const MsgServiceServiceName = "sentinel.subscription.v2.MsgService";
export class MsgServiceClientImpl implements MsgService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceServiceName;
    this.rpc = rpc;
    this.MsgAllocate = this.MsgAllocate.bind(this);
    this.MsgCancel = this.MsgCancel.bind(this);
  }
  MsgAllocate(request: MsgAllocateRequest): Promise<MsgAllocateResponse> {
    const data = MsgAllocateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgAllocate", data);
    return promise.then((data) => MsgAllocateResponse.decode(new BinaryReader(data)));
  }

  MsgCancel(request: MsgCancelRequest): Promise<MsgCancelResponse> {
    const data = MsgCancelRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MsgCancel", data);
    return promise.then((data) => MsgCancelResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
