// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: gogoproto/gogo.proto

/* eslint-disable */

export const protobufPackage = "gogoproto";
