// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v4.25.9
// source: amino/amino.proto

/* eslint-disable */

export const protobufPackage = "amino";
